### ISSUE TITLE
Listen to the theme change event in real time

### ISSUE THREAD

**Issue by proninyaroslav** [Merrit/flutter_flatpak#2]
When I change the theme on the system, for example in GNOME 42 (Fedora 36), the theme changes in real time and there is no way in the plugin to listen for these changes so that the app can react to the theme change. It's probably necessary to setup a D-Bus listener. We can use [dbus](https://pub.dev/packages/dbus) package for this purpose.

**Comment by Merrit** [comment]
Good idea. I was wondering if there was a way to subscribe to these changes, but didn't get around to checking.

I looked just now and it seems there is a `SettingChanged` signal available in `org.freedesktop.portal.Settings`, so I guess we could do something like:

- Listen for these change events, then:
  - Re-check the theme preference
  	- If it has changed, emit a new item in our own stream.

I'll play around with it when I have a few minutes. :smiley:

**Comment by Merrit** [comment]
Added with #4, seems to work well so far in my brief testing. Further confirmation also appreciated :smiley:
